# Generated by Django 4.0.3 on 2022-12-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_question_answer_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='answer',
            name='answered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
